export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CONFIRMAR_ORDENAR_PLATILLO = "CONFIRMAR_ORDENAR_PLATILLO";
export const MOSTRAR_RESUMEN = "MOSTRAR_RESUMEN";
export const ELIMINAR_PRODUCTO_CARRITO = "ELIMINAR_PRODUCTO_CARRITO";
export const PEDIDO_ORDENADO = "PEDIDO_ORDENADO";
